// <auto-generated />
using System;
using LibraCore.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraCore.Infrastructure.Migrations
{
    [DbContext(typeof(LibraCoreDbContext))]
    [Migration("20260402174929_SeedAuthorGenreAndApplicationUserData")]
    partial class SeedAuthorGenreAndApplicationUserData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1d8e8b0-2001-4b2f-8a0a-000000000201"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONC-00000001",
                            Email = "admin@libra.local",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LIBRA.LOCAL",
                            NormalizedUserName = "ADMIN@LIBRA.LOCAL",
                            PasswordHash = "AQAAAAIAAYagAAAAEKjN7j2ZtxochN+mtOPtBR4LK0g3ORE5+xRTwfu8QpHUmIFwR9aLMZpY4rAvAGsMKw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "A1D8E8B0-2001-4B2F-8A0A-000000000201",
                            TwoFactorEnabled = false,
                            UserName = "admin@libra.local"
                        },
                        new
                        {
                            Id = new Guid("c1d8e8b0-2002-4b2f-8a0a-000000000202"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONC-00000002",
                            Email = "user@libra.local",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@LIBRA.LOCAL",
                            NormalizedUserName = "USER@LIBRA.LOCAL",
                            PasswordHash = "AQAAAAIAAYagAAAAEI+LOo2C1b6jJ2aaIslMpkyTI3jGxMorfDLd8F8CshNatDHbHwStqlOF30fKIiWe/A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "A1D8E8B0-2002-4B2F-8A0A-000000000202",
                            TwoFactorEnabled = false,
                            UserName = "user@libra.local"
                        });
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1d8e8b0-1001-4b2f-8a0a-000000000101"),
                            Name = "Jane Austen"
                        },
                        new
                        {
                            Id = new Guid("b1d8e8b0-1002-4b2f-8a0a-000000000102"),
                            Name = "Charles Dickens"
                        },
                        new
                        {
                            Id = new Guid("b1d8e8b0-1003-4b2f-8a0a-000000000103"),
                            Name = "Mark Twain"
                        },
                        new
                        {
                            Id = new Guid("b1d8e8b0-1004-4b2f-8a0a-000000000104"),
                            Name = "George Orwell"
                        },
                        new
                        {
                            Id = new Guid("b1d8e8b0-1005-4b2f-8a0a-000000000105"),
                            Name = "Virginia Woolf"
                        },
                        new
                        {
                            Id = new Guid("b1d8e8b0-1006-4b2f-8a0a-000000000106"),
                            Name = "F. Scott Fitzgerald"
                        },
                        new
                        {
                            Id = new Guid("b1d8e8b0-1007-4b2f-8a0a-000000000107"),
                            Name = "J.K. Rowling"
                        },
                        new
                        {
                            Id = new Guid("b1d8e8b0-1008-4b2f-8a0a-000000000108"),
                            Name = "Stephen King"
                        },
                        new
                        {
                            Id = new Guid("b1d8e8b0-1009-4b2f-8a0a-000000000109"),
                            Name = "Agatha Christie"
                        },
                        new
                        {
                            Id = new Guid("b1d8e8b0-100a-4b2f-8a0a-00000000010a"),
                            Name = "J.R.R. Tolkien"
                        },
                        new
                        {
                            Id = new Guid("b1d8e8b0-100b-4b2f-8a0a-00000000010b"),
                            Name = "Ernest Hemingway"
                        },
                        new
                        {
                            Id = new Guid("b1d8e8b0-100c-4b2f-8a0a-00000000010c"),
                            Name = "Leo Tolstoy"
                        },
                        new
                        {
                            Id = new Guid("b1d8e8b0-100d-4b2f-8a0a-00000000010d"),
                            Name = "Isabel Allende"
                        },
                        new
                        {
                            Id = new Guid("b1d8e8b0-100e-4b2f-8a0a-00000000010e"),
                            Name = "Toni Morrison"
                        },
                        new
                        {
                            Id = new Guid("b1d8e8b0-100f-4b2f-8a0a-00000000010f"),
                            Name = "Haruki Murakami"
                        });
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("GenreID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GenreID");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1f8e8b0-0001-4b2f-8a0a-000000000001"),
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = new Guid("a1f8e8b0-0002-4b2f-8a0a-000000000002"),
                            Name = "Non-Fiction"
                        },
                        new
                        {
                            Id = new Guid("a1f8e8b0-0003-4b2f-8a0a-000000000003"),
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = new Guid("a1f8e8b0-0004-4b2f-8a0a-000000000004"),
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = new Guid("a1f8e8b0-0005-4b2f-8a0a-000000000005"),
                            Name = "Romance"
                        },
                        new
                        {
                            Id = new Guid("a1f8e8b0-0006-4b2f-8a0a-000000000006"),
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = new Guid("a1f8e8b0-0007-4b2f-8a0a-000000000007"),
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = new Guid("a1f8e8b0-0008-4b2f-8a0a-000000000008"),
                            Name = "Biography"
                        },
                        new
                        {
                            Id = new Guid("a1f8e8b0-0009-4b2f-8a0a-000000000009"),
                            Name = "History"
                        },
                        new
                        {
                            Id = new Guid("a1f8e8b0-000a-4b2f-8a0a-00000000000a"),
                            Name = "Children's"
                        },
                        new
                        {
                            Id = new Guid("a1f8e8b0-000b-4b2f-8a0a-00000000000b"),
                            Name = "Young Adult"
                        },
                        new
                        {
                            Id = new Guid("a1f8e8b0-000c-4b2f-8a0a-00000000000c"),
                            Name = "Horror"
                        },
                        new
                        {
                            Id = new Guid("a1f8e8b0-000d-4b2f-8a0a-00000000000d"),
                            Name = "Poetry"
                        },
                        new
                        {
                            Id = new Guid("a1f8e8b0-000e-4b2f-8a0a-00000000000e"),
                            Name = "Self-Help"
                        },
                        new
                        {
                            Id = new Guid("a1f8e8b0-000f-4b2f-8a0a-00000000000f"),
                            Name = "Graphic Novel"
                        });
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrdersItems");
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.UserBook", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("UsersBooks");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.Book", b =>
                {
                    b.HasOne("LibraCore.Infrastructure.Data.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraCore.Infrastructure.Data.Entities.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.Order", b =>
                {
                    b.HasOne("LibraCore.Infrastructure.Data.Entities.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("LibraCore.Infrastructure.Data.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraCore.Infrastructure.Data.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.Review", b =>
                {
                    b.HasOne("LibraCore.Infrastructure.Data.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraCore.Infrastructure.Data.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.UserBook", b =>
                {
                    b.HasOne("LibraCore.Infrastructure.Data.Entities.Book", "Book")
                        .WithMany("UsersBooks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraCore.Infrastructure.Data.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("LibraCore.Infrastructure.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("LibraCore.Infrastructure.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraCore.Infrastructure.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("LibraCore.Infrastructure.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.Book", b =>
                {
                    b.Navigation("UsersBooks");
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
