// <auto-generated />
using System;
using LibraCore.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraCore.Infrastructure.Migrations
{
    [DbContext(typeof(LibraCoreDbContext))]
    [Migration("20260402182418_SeedBooks")]
    partial class SeedBooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1d8e8b0-2001-4b2f-8a0a-000000000201"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONC-00000001",
                            Email = "admin@libra.local",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LIBRA.LOCAL",
                            NormalizedUserName = "ADMIN@LIBRA.LOCAL",
                            PasswordHash = "AQAAAAIAAYagAAAAEHuGlvUJqBvQ8MDINKSFxAtCd71/e2ATlESz3PAOfUJf0KjIhJWXjhreSd4cnx468w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "A1D8E8B0-2001-4B2F-8A0A-000000000201",
                            TwoFactorEnabled = false,
                            UserName = "admin@libra.local"
                        },
                        new
                        {
                            Id = new Guid("c1d8e8b0-2002-4b2f-8a0a-000000000202"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONC-00000002",
                            Email = "user@libra.local",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@LIBRA.LOCAL",
                            NormalizedUserName = "USER@LIBRA.LOCAL",
                            PasswordHash = "AQAAAAIAAYagAAAAEABECB81eY+iz1mtCWLjZTiAdx8hNdb2NM5/gxrQZMi/YNWoK/c+TYnrbK8iQfnvbw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "A1D8E8B0-2002-4B2F-8A0A-000000000202",
                            TwoFactorEnabled = false,
                            UserName = "user@libra.local"
                        });
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1d8e8b0-1001-4b2f-8a0a-000000000101"),
                            IsDeleted = false,
                            Name = "Jane Austen"
                        },
                        new
                        {
                            Id = new Guid("b1d8e8b0-1002-4b2f-8a0a-000000000102"),
                            IsDeleted = false,
                            Name = "Charles Dickens"
                        },
                        new
                        {
                            Id = new Guid("b1d8e8b0-1003-4b2f-8a0a-000000000103"),
                            IsDeleted = false,
                            Name = "Mark Twain"
                        },
                        new
                        {
                            Id = new Guid("b1d8e8b0-1004-4b2f-8a0a-000000000104"),
                            IsDeleted = false,
                            Name = "George Orwell"
                        },
                        new
                        {
                            Id = new Guid("b1d8e8b0-1005-4b2f-8a0a-000000000105"),
                            IsDeleted = false,
                            Name = "Virginia Woolf"
                        },
                        new
                        {
                            Id = new Guid("b1d8e8b0-1006-4b2f-8a0a-000000000106"),
                            IsDeleted = false,
                            Name = "F. Scott Fitzgerald"
                        },
                        new
                        {
                            Id = new Guid("b1d8e8b0-1007-4b2f-8a0a-000000000107"),
                            IsDeleted = false,
                            Name = "J.K. Rowling"
                        },
                        new
                        {
                            Id = new Guid("b1d8e8b0-1008-4b2f-8a0a-000000000108"),
                            IsDeleted = false,
                            Name = "Stephen King"
                        },
                        new
                        {
                            Id = new Guid("b1d8e8b0-1009-4b2f-8a0a-000000000109"),
                            IsDeleted = false,
                            Name = "Agatha Christie"
                        },
                        new
                        {
                            Id = new Guid("b1d8e8b0-100a-4b2f-8a0a-00000000010a"),
                            IsDeleted = false,
                            Name = "J.R.R. Tolkien"
                        },
                        new
                        {
                            Id = new Guid("b1d8e8b0-100b-4b2f-8a0a-00000000010b"),
                            IsDeleted = false,
                            Name = "Ernest Hemingway"
                        },
                        new
                        {
                            Id = new Guid("b1d8e8b0-100c-4b2f-8a0a-00000000010c"),
                            IsDeleted = false,
                            Name = "Leo Tolstoy"
                        },
                        new
                        {
                            Id = new Guid("b1d8e8b0-100d-4b2f-8a0a-00000000010d"),
                            IsDeleted = false,
                            Name = "Isabel Allende"
                        },
                        new
                        {
                            Id = new Guid("b1d8e8b0-100e-4b2f-8a0a-00000000010e"),
                            IsDeleted = false,
                            Name = "Toni Morrison"
                        },
                        new
                        {
                            Id = new Guid("b1d8e8b0-100f-4b2f-8a0a-00000000010f"),
                            IsDeleted = false,
                            Name = "Haruki Murakami"
                        });
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("GenreID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GenreID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1b8e8b0-3001-4b2f-8a0a-000000000301"),
                            AuthorId = new Guid("b1d8e8b0-1001-4b2f-8a0a-000000000101"),
                            Description = "A classic romantic novel about manners and marriage.",
                            GenreID = new Guid("a1f8e8b0-0005-4b2f-8a0a-000000000005"),
                            ImageUrl = "https://s3.amazonaws.com/nightjarprod/content/uploads/sites/192/2025/12/02152113/v5gShop7147X33ytbcC2u05KDuc.jpg",
                            IsDeleted = false,
                            Price = 9.99m,
                            ReleaseDate = new DateOnly(1813, 1, 28),
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = new Guid("d1b8e8b0-3002-4b2f-8a0a-000000000302"),
                            AuthorId = new Guid("b1d8e8b0-1002-4b2f-8a0a-000000000102"),
                            Description = "The growth and personal development of an orphan named Pip.",
                            GenreID = new Guid("a1f8e8b0-0001-4b2f-8a0a-000000000001"),
                            ImageUrl = "https://m.media-amazon.com/images/I/815ZFQcdRcL._AC_UF1000,1000_QL80_.jpg",
                            IsDeleted = false,
                            Price = 11.50m,
                            ReleaseDate = new DateOnly(1861, 8, 1),
                            Title = "Great Expectations"
                        },
                        new
                        {
                            Id = new Guid("d1b8e8b0-3003-4b2f-8a0a-000000000303"),
                            AuthorId = new Guid("b1d8e8b0-1003-4b2f-8a0a-000000000103"),
                            Description = "A young boy's adventures along the Mississippi River.",
                            GenreID = new Guid("a1f8e8b0-0001-4b2f-8a0a-000000000001"),
                            ImageUrl = "https://m.media-amazon.com/images/I/91sBZnKzEfL._AC_UF1000,1000_QL80_.jpg",
                            IsDeleted = false,
                            Price = 10.00m,
                            ReleaseDate = new DateOnly(1884, 12, 10),
                            Title = "Adventures of Huckleberry Finn"
                        },
                        new
                        {
                            Id = new Guid("d1b8e8b0-3004-4b2f-8a0a-000000000304"),
                            AuthorId = new Guid("b1d8e8b0-1004-4b2f-8a0a-000000000104"),
                            Description = "A dystopian novel about surveillance and totalitarianism.",
                            GenreID = new Guid("a1f8e8b0-0007-4b2f-8a0a-000000000007"),
                            ImageUrl = "https://m.media-amazon.com/images/I/71wANojhEKL._AC_UF1000,1000_QL80_.jpg",
                            IsDeleted = false,
                            Price = 12.99m,
                            ReleaseDate = new DateOnly(1949, 6, 8),
                            Title = "1984"
                        },
                        new
                        {
                            Id = new Guid("d1b8e8b0-3005-4b2f-8a0a-000000000305"),
                            AuthorId = new Guid("b1d8e8b0-1005-4b2f-8a0a-000000000105"),
                            Description = "A day in the life of Clarissa Dalloway in post‑war London.",
                            GenreID = new Guid("a1f8e8b0-0001-4b2f-8a0a-000000000001"),
                            ImageUrl = "https://www.book.store.bg/lrgimg/779190437/mrs-dalloway.jpg",
                            IsDeleted = false,
                            Price = 8.75m,
                            ReleaseDate = new DateOnly(1925, 5, 14),
                            Title = "Mrs Dalloway"
                        },
                        new
                        {
                            Id = new Guid("d1b8e8b0-3006-4b2f-8a0a-000000000306"),
                            AuthorId = new Guid("b1d8e8b0-1006-4b2f-8a0a-000000000106"),
                            Description = "A story of the Jazz Age and the decline of the American Dream.",
                            GenreID = new Guid("a1f8e8b0-0001-4b2f-8a0a-000000000001"),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/7/7a/The_Great_Gatsby_Cover_1925_Retouched.jpg",
                            IsDeleted = false,
                            Price = 9.50m,
                            ReleaseDate = new DateOnly(1925, 4, 10),
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = new Guid("d1b8e8b0-3007-4b2f-8a0a-000000000307"),
                            AuthorId = new Guid("b1d8e8b0-1007-4b2f-8a0a-000000000107"),
                            Description = "The first book in the Harry Potter series; a young wizard begins his journey.",
                            GenreID = new Guid("a1f8e8b0-0006-4b2f-8a0a-000000000006"),
                            ImageUrl = "https://cdn.ozone.bg/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/h/a/a19438e622aa321a0e73f360f1f3f855/harry-potter-and-the-philosopher-s-stone-30.jpg",
                            IsDeleted = false,
                            Price = 14.99m,
                            ReleaseDate = new DateOnly(1997, 6, 26),
                            Title = "Harry Potter and the Philosopher's Stone"
                        },
                        new
                        {
                            Id = new Guid("d1b8e8b0-3008-4b2f-8a0a-000000000308"),
                            AuthorId = new Guid("b1d8e8b0-1008-4b2f-8a0a-000000000108"),
                            Description = "A chilling horror novel set in an isolated hotel.",
                            GenreID = new Guid("a1f8e8b0-000c-4b2f-8a0a-00000000000c"),
                            ImageUrl = "https://m.media-amazon.com/images/I/91U7HNa2NQL._AC_UF1000,1000_QL80_.jpg",
                            IsDeleted = false,
                            Price = 13.50m,
                            ReleaseDate = new DateOnly(1977, 1, 28),
                            Title = "The Shining"
                        },
                        new
                        {
                            Id = new Guid("d1b8e8b0-3009-4b2f-8a0a-000000000309"),
                            AuthorId = new Guid("b1d8e8b0-1009-4b2f-8a0a-000000000109"),
                            Description = "A Hercule Poirot mystery on a snowbound train.",
                            GenreID = new Guid("a1f8e8b0-0003-4b2f-8a0a-000000000003"),
                            ImageUrl = "https://m.media-amazon.com/images/I/81aY+Fk-g8L._UF1000,1000_QL80_.jpg",
                            IsDeleted = false,
                            Price = 10.99m,
                            ReleaseDate = new DateOnly(1934, 1, 1),
                            Title = "Murder on the Orient Express"
                        },
                        new
                        {
                            Id = new Guid("d1b8e8b0-300a-4b2f-8a0a-00000000030a"),
                            AuthorId = new Guid("b1d8e8b0-100a-4b2f-8a0a-00000000010a"),
                            Description = "A fantasy adventure that precedes the Lord of the Rings.",
                            GenreID = new Guid("a1f8e8b0-0006-4b2f-8a0a-000000000006"),
                            ImageUrl = "https://m.media-amazon.com/images/I/81uEDUfKBZL.jpg",
                            IsDeleted = false,
                            Price = 12.00m,
                            ReleaseDate = new DateOnly(1937, 9, 21),
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = new Guid("d1b8e8b0-300b-4b2f-8a0a-00000000030b"),
                            AuthorId = new Guid("b1d8e8b0-100c-4b2f-8a0a-00000000010c"),
                            Description = "An epic novel following several families during the Napoleonic era.",
                            GenreID = new Guid("a1f8e8b0-0009-4b2f-8a0a-000000000009"),
                            ImageUrl = "https://m.media-amazon.com/images/I/81W6BFaJJWL._AC_UF1000,1000_QL80_.jpg",
                            IsDeleted = false,
                            Price = 15.00m,
                            ReleaseDate = new DateOnly(1869, 1, 1),
                            Title = "War and Peace"
                        });
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1f8e8b0-0001-4b2f-8a0a-000000000001"),
                            IsDeleted = false,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = new Guid("a1f8e8b0-0002-4b2f-8a0a-000000000002"),
                            IsDeleted = false,
                            Name = "Non-Fiction"
                        },
                        new
                        {
                            Id = new Guid("a1f8e8b0-0003-4b2f-8a0a-000000000003"),
                            IsDeleted = false,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = new Guid("a1f8e8b0-0004-4b2f-8a0a-000000000004"),
                            IsDeleted = false,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = new Guid("a1f8e8b0-0005-4b2f-8a0a-000000000005"),
                            IsDeleted = false,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = new Guid("a1f8e8b0-0006-4b2f-8a0a-000000000006"),
                            IsDeleted = false,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = new Guid("a1f8e8b0-0007-4b2f-8a0a-000000000007"),
                            IsDeleted = false,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = new Guid("a1f8e8b0-0008-4b2f-8a0a-000000000008"),
                            IsDeleted = false,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = new Guid("a1f8e8b0-0009-4b2f-8a0a-000000000009"),
                            IsDeleted = false,
                            Name = "History"
                        },
                        new
                        {
                            Id = new Guid("a1f8e8b0-000a-4b2f-8a0a-00000000000a"),
                            IsDeleted = false,
                            Name = "Children's"
                        },
                        new
                        {
                            Id = new Guid("a1f8e8b0-000b-4b2f-8a0a-00000000000b"),
                            IsDeleted = false,
                            Name = "Young Adult"
                        },
                        new
                        {
                            Id = new Guid("a1f8e8b0-000c-4b2f-8a0a-00000000000c"),
                            IsDeleted = false,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = new Guid("a1f8e8b0-000d-4b2f-8a0a-00000000000d"),
                            IsDeleted = false,
                            Name = "Poetry"
                        },
                        new
                        {
                            Id = new Guid("a1f8e8b0-000e-4b2f-8a0a-00000000000e"),
                            IsDeleted = false,
                            Name = "Self-Help"
                        },
                        new
                        {
                            Id = new Guid("a1f8e8b0-000f-4b2f-8a0a-00000000000f"),
                            IsDeleted = false,
                            Name = "Graphic Novel"
                        });
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrdersItems");
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.UserBook", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("UsersBooks");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.Book", b =>
                {
                    b.HasOne("LibraCore.Infrastructure.Data.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraCore.Infrastructure.Data.Entities.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.Order", b =>
                {
                    b.HasOne("LibraCore.Infrastructure.Data.Entities.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("LibraCore.Infrastructure.Data.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraCore.Infrastructure.Data.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.Review", b =>
                {
                    b.HasOne("LibraCore.Infrastructure.Data.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraCore.Infrastructure.Data.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.UserBook", b =>
                {
                    b.HasOne("LibraCore.Infrastructure.Data.Entities.Book", "Book")
                        .WithMany("UsersBooks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraCore.Infrastructure.Data.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("LibraCore.Infrastructure.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("LibraCore.Infrastructure.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraCore.Infrastructure.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("LibraCore.Infrastructure.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.Book", b =>
                {
                    b.Navigation("UsersBooks");
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraCore.Infrastructure.Data.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
